version: '3.9'
name: challenge-crf

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq-server'
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks: 
            - rabbitmq_go_net

    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

    ChallengeCrf.Queue.Worker:
        image: challengecrf.queue.worker
        build:
            context: .
            dockerfile: Src/ChallengeCrf.Worker/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Stage
        ports:
            - 5100:5100
            
    ChallengeCrf.Api:
        image: challengecrf.api
        build:
            context: .
            dockerfile: Src/ChallengeCrf.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Stage
        ports:
            - 5200:5200
            
networks:
    rabbitmq_go_net:
        driver: bridge